export const DELETE_SNEAKER = 'DELETE_SNEAKER';

export const ADD_SNEAKER_REQUEST = 'ADD_SNEAKER_REQUEST';
export const ADD_SNEAKER_SUCCESS = 'ADD_SNEAKER_SUCCESS';
export const ADD_SNEAKER_ERROR = 'ADD_SNEAKER_ERROR';

export const CLEAR_SNEAKERS = 'CLEAR_SNEAKERS';
